//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibHeifSharp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LibHeifSharp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method requires LibHeif version 1.11.0 or later..
        /// </summary>
        internal static string AuxiliaryImageAPINotSupported {
            get {
                return ResourceManager.GetString("AuxiliaryImageAPINotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get all of the auxiliary images..
        /// </summary>
        internal static string CannotGetAllAuxillaryImages {
            get {
                return ResourceManager.GetString("CannotGetAllAuxillaryImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get all of the decoder descriptors..
        /// </summary>
        internal static string CannotGetAllDecoderDescriptors {
            get {
                return ResourceManager.GetString("CannotGetAllDecoderDescriptors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get all of the decoding warnings..
        /// </summary>
        internal static string CannotGetAllDecodingWarnings {
            get {
                return ResourceManager.GetString("CannotGetAllDecodingWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get all of the meta-data block ids..
        /// </summary>
        internal static string CannotGetAllMetadataBlockIds {
            get {
                return ResourceManager.GetString("CannotGetAllMetadataBlockIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get all of the thumbnail ids..
        /// </summary>
        internal static string CannotGetAllThumbnailIds {
            get {
                return ResourceManager.GetString("CannotGetAllThumbnailIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get all of the top-level image ids..
        /// </summary>
        internal static string CannotGetAllTopLevelImageIds {
            get {
                return ResourceManager.GetString("CannotGetAllTopLevelImageIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to convert the {0} parameter to a Boolean..
        /// </summary>
        internal static string CoerceStringValueToBooleanFailedFormat {
            get {
                return ResourceManager.GetString("CoerceStringValueToBooleanFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to convert the {0} parameter to an integer..
        /// </summary>
        internal static string CoerceStringValueToIntegerFailedFormat {
            get {
                return ResourceManager.GetString("CoerceStringValueToIntegerFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The color profile type is not supported..
        /// </summary>
        internal static string ColorProfileTypeNotSupported {
            get {
                return ResourceManager.GetString("ColorProfileTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device does not support seeking..
        /// </summary>
        internal static string FileStreamDoesNotSupportSeeking {
            get {
                return ResourceManager.GetString("FileStreamDoesNotSupportSeeking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This HeifContext already has an associated reader..
        /// </summary>
        internal static string HeifContextAlreadyHasReader {
            get {
                return ResourceManager.GetString("HeifContextAlreadyHasReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create the native HeifContext..
        /// </summary>
        internal static string HeifContextCreationFailed {
            get {
                return ResourceManager.GetString("HeifContextCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create the native HeifDecodingOptions..
        /// </summary>
        internal static string HeifDecodingOptionsCreationFailed {
            get {
                return ResourceManager.GetString("HeifDecodingOptionsCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create the native HeifEncodingOptions..
        /// </summary>
        internal static string HeifEncodingOptionsCreationFailed {
            get {
                return ResourceManager.GetString("HeifEncodingOptionsCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ICC profile is larger than 2 GB..
        /// </summary>
        internal static string IccProfileLargerThan2Gb {
            get {
                return ResourceManager.GetString("IccProfileLargerThan2Gb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ICC profile is zero bytes..
        /// </summary>
        internal static string IccProfileZeroBytes {
            get {
                return ResourceManager.GetString("IccProfileZeroBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image does not contain the specified channel..
        /// </summary>
        internal static string ImageDoesNotContainChannel {
            get {
                return ResourceManager.GetString("ImageDoesNotContainChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image has an undefined bit depth..
        /// </summary>
        internal static string ImageUndefinedBitDepth {
            get {
                return ResourceManager.GetString("ImageUndefinedBitDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LibHeif must be version {0}.{1}.{2} or later..
        /// </summary>
        internal static string LibHeifVersionNotSupportedFormat {
            get {
                return ResourceManager.GetString("LibHeifVersionNotSupportedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The meta-data block is larger than 2 GB..
        /// </summary>
        internal static string MetadataBlockLargerThan2Gb {
            get {
                return ResourceManager.GetString("MetadataBlockLargerThan2Gb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create the native NCLX color profile..
        /// </summary>
        internal static string NclxProfileCreationFailed {
            get {
                return ResourceManager.GetString("NclxProfileCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file does not have any top-level images..
        /// </summary>
        internal static string NoTopLevelImages {
            get {
                return ResourceManager.GetString("NoTopLevelImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is an empty array..
        /// </summary>
        internal static string ParameterIsEmptyArrayFormat {
            get {
                return ResourceManager.GetString("ParameterIsEmptyArrayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a positive number..
        /// </summary>
        internal static string ParameterMustBePositive {
            get {
                return ResourceManager.GetString("ParameterMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is empty or contains only whitespace characters..
        /// </summary>
        internal static string ParameterStringIsEmptyOrWhitespaceFormat {
            get {
                return ResourceManager.GetString("ParameterStringIsEmptyOrWhitespaceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A reader must be set before calling before this method..
        /// </summary>
        internal static string ReaderNotSet {
            get {
                return ResourceManager.GetString("ReaderNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream must support reading and seeking..
        /// </summary>
        internal static string StreamCannotReadAndSeek {
            get {
                return ResourceManager.GetString("StreamCannotReadAndSeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream must support writing..
        /// </summary>
        internal static string StreamCannotWrite {
            get {
                return ResourceManager.GetString("StreamCannotWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unspecified error occurred..
        /// </summary>
        internal static string UnspecifiedError {
            get {
                return ResourceManager.GetString("UnspecifiedError", resourceCulture);
            }
        }
    }
}
